name: 'test_ci'
description: 'test'

inputs:
  network:
    description: "List of networks you want to deploy on"
    required: true
  deploy-command:
    description: "Command to deploy the contract"
    required: true
  buildbear-token:
    description: "Buildbear API token"
    required: true
  working-directory:
    description: "Project directory"
    required: false
    default: "."
  slack-webhook-url:
    description: "Slack Webhook URL to send notifications"
    required: false  

outputs:
  deployments:
    description: 'deployments logs'
     
runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'bold'
  color: 'green'  
