name: 'bb_action_ci'
description: 'BB'

inputs:
  network:
    description: 'List of networks you want to deploy on'
    required: true
  deployCmd:
    description: 'Command to deploy the contract'
    required: true
  buildbear_token: 
    description: "Buildbear API token"
    required: true

outputs:
  deployments:
    description: 'deployments logs'
     
runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'activity'
  color: 'green'  
